In [3]:
import pandas as pd
import os

In [29]:
train_folder = "./data/train"

files = {
    "additional": "additional_features_train.csv",
    "basic": "basic_features_train.csv",
    "content": "content_features_train.csv",
    "flow": "flow_features_train.csv",
    "time": "time_features_train.csv",
    "labels": "labels_train.csv"
}

def load_csv(file_name):
    return pd.read_csv(os.path.join(train_folder, file_name))

data = {name: load_csv(file) for name, file in files.items()}

modified_features_df = pd.read_csv(os.path.join(train_folder, "UNSW-NB15_features-modified.csv"))

In [37]:
df = data['basic']
for key, datas in data.items():
    if key != 'basic':
        df = pd.merge(df, datas, on='id', how='inner')
df.drop(columns=["label"], inplace=True)  # unusued

df.head()

,state,dur,sbytes,dbytes,sttl,dttl,sloss,dloss,service,sload,...,response_body_len,proto,sjit,djit,sinpkt,dinpkt,tcprtt,synack,ackdat,attack_cat
0,FIN,2.736664,13350.0,548216.0,31.0,29.0,21.0,197.0,-,3.885899e+04,...,0.0,tcp,4449.110313,3234.831566,11.845558,6.261361,NaN,0.000444,0.000114,Normal
1,INT,0.000009,114.0,0.0,254.0,0.0,0.0,0.0,dns,5.066666e+07,...,0.0,udp,0.000000,0.000000,0.009000,0.000000,0.000000,0.000000,NaN,Generic
2,FIN,5.788526,6102.0,3892.0,254.0,252.0,13.0,13.0,-,8.199669e+03,...,0.0,tcp,8561.040438,249.950547,165.386453,172.345750,0.158826,0.057902,0.100924,Exploits
3,FIN,3.849634,25160.0,NaN,31.0,29.0,38.0,390.0,-,5.216912e+04,...,0.0,tcp,4053.086020,2918.730804,8.669644,4.496707,0.000558,0.000448,NaN,Normal
4,CON,0.001052,130.0,162.0,NaN,29.0,0.0,0.0,dns,4.942966e+05,...,0.0,udp,0.000000,0.000000,0.008000,0.007000,0.000000,0.000000,0.000000,Normal

In [38]:
print(df.shape)
df.describe()

(175341, 43)

,dur,sbytes,dbytes,sttl,dttl,sloss,dloss,sload,dload,spkts,...,dmean,trans_depth,response_body_len,sjit,djit,sinpkt,dinpkt,tcprtt,synack,ackdat
count,166619.000000,1.667800e+05,1.664720e+05,166516.000000,166687.000000,166547.000000,166363.000000,1.665550e+05,1.665040e+05,166687.000000,...,166486.000000,166556.000000,1.665500e+05,1.666030e+05,166495.000000,166634.000000,166607.000000,166505.000000,166605.000000,166746.000000
mean,1.359299,8.734079e+03,1.493589e+04,179.521944,79.584179,4.904790,6.971688,7.342186e+07,6.718596e+05,20.266134,...,124.161041,0.106193,2.157133e+03,4.993982e+03,604.891720,987.360974,87.763617,0.041331,0.021042,0.020402
std,6.485386,1.712289e+05,1.430150e+05,102.957427,110.494848,64.867849,51.801936,1.884564e+08,2.422879e+06,136.433895,...,258.265755,0.794070,5.509898e+04,4.506783e+04,4082.439167,7246.462797,987.040024,0.079428,0.043560,0.040619
min,0.000000,2.800000e+01,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,1.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000008,1.140000e+02,0.000000e+00,62.000000,0.000000,0.000000,0.000000,1.303032e+04,0.000000e+00,2.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.008000,0.000000,0.000000,0.000000,0.000000
50%,0.001548,4.500000e+02,1.640000e+02,254.000000,29.000000,0.000000,0.000000,8.714544e+05,1.426630e+03,2.000000,...,44.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.284723,0.006000,0.000000,0.000000,0.000000
75%,0.667311,1.418000e+03,1.096000e+03,254.000000,252.000000,3.000000,2.000000,8.888889e+07,2.807410e+04,12.000000,...,89.000000,0.000000,0.000000e+00,2.511184e+03,114.753348,55.205806,50.933127,0.065151,0.023235,0.038951
max,59.999989,1.296523e+07,1.465555e+07,255.000000,254.000000,4803.000000,5484.000000,5.988000e+09,2.242273e+07,9616.000000,...,1458.000000,172.000000,6.558056e+06,1.460480e+06,289388.269700,84371.496000,56716.824000,2.518893,2.100352,1.520884

In [30]:
display(modified_features_df)

,No.,Name,Type,Description,feature_type
0,5,proto,nominal,Transaction protocol,flow
1,6,state,nominal,Indicates to the state and its dependent proto...,basic
2,7,dur,Float,Record total duration,basic
3,8,sbytes,Integer,Source to destination transaction bytes,basic
4,9,dbytes,Integer,Destination to source transaction bytes,basic
5,10,sttl,Integer,Source to destination time to live value,basic
6,11,dttl,Integer,Destination to source time to live value,basic
7,12,sloss,Integer,Source packets retransmitted or dropped,basic
8,13,dloss,Integer,Destination packets retransmitted or dropped,basic
9,14,service,nominal,"http, ftp, smtp, ssh, dns, ftp-data ,irc and ...",basic
10,15,sload,Float,Source bits per second,basic
11,16,dload,Float,Destination bits per second,basic
12,17,spkts,integer,Source to destination packet count,basic
13,18,dpkts,integer,Destination to source packet count,basic
14,19,swin,integer,Source TCP window advertisement value,content
15,20,dwin,integer,Destination TCP window advertisement value,content
16,21,stcpb,integer,Source TCP base sequence number,content
17,22,dtcpb,integer,Destination TCP base sequence number,content
18,23,smean,integer,Mean of the ?ow packet size transmitted by the...,content
19,24,dmean,integer,Mean of the ?ow packet size transmitted by the...,content
20,25,trans_depth,integer,Represents the pipelined depth into the connec...,content
21,26,response_body_len,integer,Actual uncompressed content size of the data t...,content
22,27,sjit,Float,Source jitter (mSec),time
23,28,djit,Float,Destination jitter (mSec),time
24,31,sinpkt,Float,Source interpacket arrival time (mSec),time
25,32,dinpkt,Float,Destination interpacket arrival time (mSec),time
26,33,tcprtt,Float,"TCP connection setup round-trip time, the sum ...",time
27,34,synack,Float,"TCP connection setup time, the time between th...",time
28,35,ackdat,Float,"TCP connection setup time, the time between th...",time
29,36,is_sm_ips_ports,Binary,If source (1) and destination (3)IP addresses ...,additional
30,37,ct_state_ttl,Integer,No. for each state (6) according to specific r...,additional
31,38,ct_flw_http_mthd,Integer,No. of flows that has methods such as Get and ...,additional
32,39,is_ftp_login,Binary,If the ftp session is accessed by user and pas...,additional
33,40,ct_ftp_cmd,integer,No of flows that has a command in ftp session.,additional
34,41,ct_srv_src,integer,No. of connections that contain the same servi...,additional
35,42,ct_srv_dst,integer,No. of connections that contain the same servi...,additional
36,43,ct_dst_ltm,integer,No. of connections of the same destination add...,additional
37,44,ct_src_ltm,integer,No. of connections of the same source address ...,additional
38,45,ct_src_dport_ltm,integer,No of connections of the same source address (...,additional
39,46,ct_dst_sport_ltm,integer,No of connections of the same destination addr...,additional
40,47,ct_dst_src_ltm,integer,No of connections of the same source (1) and t...,additional
41,48,attack_cat,nominal,The name of each attack category. In this data...,label
42,49,label,binary,0 for normal and 1 for attack records,label

In [20]:
df.isnull().sum()

state                8805
dur                  8722
sbytes               8561
dbytes               8869
sttl                 8825
dttl                 8654
sloss                8794
dloss                8978
service              8791
sload                8786
dload                8837
spkts                8654
dpkts                8686
id                      0
is_sm_ips_ports      8746
ct_state_ttl         8635
ct_flw_http_mthd     8647
is_ftp_login         8647
ct_ftp_cmd           8842
ct_srv_src           8851
ct_srv_dst           8774
ct_dst_ltm           8738
ct_src_ltm           8823
ct_src_dport_ltm     8775
ct_dst_sport_ltm     8788
ct_dst_src_ltm       8895
swin                 8740
dwin                 8779
stcpb                8672
dtcpb                8803
smean                8788
dmean                8855
trans_depth          8785
response_body_len    8791
proto                8826
sjit                 8738
djit                 8846
sinpkt               8707
dinpkt               8734
tcprtt               8836
synack               8736
ackdat               8595
attack_cat              0
label                   0
dtype: int64

In [32]:
binary_columns = ['is_sm_ips_ports', 'is_ftp_login', 'label']


# first we check how many values in the supposed to be binary columns
for col in binary_columns:
    print(f"\n{col} unique values: {df[col].unique()}")
    print(f"{col} value counts: {df[col].value_counts()}")

is_sm_ips_ports unique values: [ 0. nan  1.]
is_sm_ips_ports value counts: is_sm_ips_ports
0.0    163963
1.0      2632
Name: count, dtype: int64

is_ftp_login unique values: [ 0. nan  1.  2.  4.]
is_ftp_login value counts: is_ftp_login
0.0    164251
1.0      2422
4.0        16
2.0         5
Name: count, dtype: int64

label unique values: [0 1]
label value counts: label
1    119341
0     56000
Name: count, dtype: int64

In [33]:
# 3. The number of unique values for each categorical features.

# Assume: We really sure the metadata is correct.
# So the categorical is when the type is other than Integer and Float
features = modified_features_df['Name']

categorical_features = modified_features_df[~modified_features_df['Type '].str.contains('integer|float', case=False, na=False)]['Name']

numerical_features = features[~features.isin(categorical_features)]


unique_values = df[categorical_features].nunique().sort_values(ascending=False)
unique_values

proto              133
service             13
attack_cat          10
state                9
is_ftp_login         4
is_sm_ips_ports      2
label                2
dtype: int64

In [34]:
# 4.


print("Numerical Features:")
display(numerical_features)

# Calculate statistical measures for numerical features
statistics = df[numerical_features].agg(['min', 'max', 'mean', 'median', 'std']).transpose()

# Rename columns for clarity
statistics = statistics.rename(columns={
    'min': 'Minimum',
    'max': 'Maximum',
    'mean': 'Mean',
    'median': 'Median',
    'std': 'Standard Deviation'
})

print("Statistical Measures for Numerical Features:")
display(statistics)

Numerical Features:

2                   dur
3                sbytes
4                dbytes
5                  sttl
6                  dttl
7                 sloss
8                 dloss
10                sload
11                dload
12                spkts
13                dpkts
14                 swin
15                 dwin
16                stcpb
17                dtcpb
18                smean
19                dmean
20          trans_depth
21    response_body_len
22                 sjit
23                 djit
24               sinpkt
25               dinpkt
26               tcprtt
27               synack
28               ackdat
30         ct_state_ttl
31     ct_flw_http_mthd
33           ct_ftp_cmd
34           ct_srv_src
35           ct_srv_dst
36           ct_dst_ltm
37           ct_src_ltm
38     ct_src_dport_ltm
39     ct_dst_sport_ltm
40       ct_dst_src_ltm
Name: Name, dtype: object

Statistical Measures for Numerical Features:

,Minimum,Maximum,Mean,Median,Standard Deviation
dur,0.0,5.999999e+01,1.359299e+00,0.001548,6.485386e+00
sbytes,28.0,1.296523e+07,8.734079e+03,450.000000,1.712289e+05
dbytes,0.0,1.465555e+07,1.493589e+04,164.000000,1.430150e+05
sttl,0.0,2.550000e+02,1.795219e+02,254.000000,1.029574e+02
dttl,0.0,2.540000e+02,7.958418e+01,29.000000,1.104948e+02
sloss,0.0,4.803000e+03,4.904790e+00,0.000000,6.486785e+01
dloss,0.0,5.484000e+03,6.971688e+00,0.000000,5.180194e+01
sload,0.0,5.988000e+09,7.342186e+07,871454.437500,1.884564e+08
dload,0.0,2.242273e+07,6.718596e+05,1426.629700,2.422879e+06
spkts,1.0,9.616000e+03,2.026613e+01,2.000000,1.364339e+02
dpkts,0.0,1.097400e+04,1.892301e+01,2.000000,1.108981e+02
swin,0.0,2.550000e+02,1.161848e+02,0.000000,1.269948e+02
dwin,0.0,2.550000e+02,1.149564e+02,0.000000,1.268809e+02
stcpb,0.0,4.294959e+09,9.696210e+08,0.000000,1.355284e+09
dtcpb,0.0,4.294882e+09,9.693479e+08,0.000000,1.354113e+09
smean,28.0,1.504000e+03,1.368038e+02,73.000000,2.047532e+02
dmean,0.0,1.458000e+03,1.241610e+02,44.000000,2.582658e+02
trans_depth,0.0,1.720000e+02,1.061925e-01,0.000000,7.940700e-01
response_body_len,0.0,6.558056e+06,2.157133e+03,0.000000,5.509898e+04
sjit,0.0,1.460480e+06,4.993982e+03,0.000000,4.506783e+04
djit,0.0,2.893883e+05,6.048917e+02,0.000000,4.082439e+03
sinpkt,0.0,8.437150e+04,9.873610e+02,0.284723,7.246463e+03
dinpkt,0.0,5.671682e+04,8.776362e+01,0.006000,9.870400e+02
tcprtt,0.0,2.518893e+00,4.133087e-02,0.000000,7.942761e-02
synack,0.0,2.100352e+00,2.104187e-02,0.000000,4.356026e-02
ackdat,0.0,1.520884e+00,2.040227e-02,0.000000,4.061870e-02
ct_state_ttl,0.0,6.000000e+00,1.303852e+00,1.000000,9.547787e-01
ct_flw_http_mthd,0.0,3.000000e+01,1.327222e-01,0.000000,6.920190e-01
ct_ftp_cmd,0.0,4.000000e+00,1.496105e-02,0.000000,1.257712e-01
ct_srv_src,1.0,6.300000e+01,9.304415e+00,5.000000,1.069978e+01
ct_srv_dst,1.0,6.200000e+01,9.104384e+00,4.000000,1.075810e+01
ct_dst_ltm,1.0,5.100000e+01,6.191773e+00,2.000000,8.050067e+00
ct_src_ltm,1.0,6.000000e+01,6.952450e+00,3.000000,8.318103e+00
ct_src_dport_ltm,1.0,5.100000e+01,5.388116e+00,1.000000,8.044942e+00
ct_dst_sport_ltm,1.0,4.600000e+01,4.198363e+00,1.000000,5.775348e+00
ct_dst_src_ltm,1.0,6.500000e+01,8.731000e+00,3.000000,1.095649e+01